use_amazon_linux:
  - no
ctng_sample:
  - powerpc64le-unknown-linux-gnu
ctng_cpu_arch:
  - powerpc64le
ctng_gcc:
  - 10.2.0
libgfortran_soname:
  - 5
ctng_binutils:
  - 2.36.1
ctng_target_platform:
  - linux-ppc64le
old_ctng_vendor:
  - conda_cos7
ctng_vendor:
  - conda
ctng_gcc_build_number:
  - 0
_libgcc_mutex:
  - 0.1 main
# ctng_duma:
#   - 2.5.15
ctng_gmp:
  - 6.2.1
ctng_isl:
  - 0.23
ctng_libc:
  - gnu
gnu:
  - 2.17
conda_glibc_ver:
  - 2.17
ctng_kernel:
  - 3.10.0
ctng_libiconv:
  - 1.16
ctng_gettext:
  - 0.20.1
ctng_mpfr:
  - 4.0.2
ctng_mpc:
  - 1.2.1
# ctng_gdb:
#   - 1
# gdb_version:
#   - 10.1
ctng_nature:
  - shared
ctng_ncurses:
  - 6.2
openmp_ver:
  - 5.1
libgomp_ver:
  - 1.0.0

zip_keys:
  - - conda_glibc_ver
    - old_ctng_vendor
    - ctng_kernel
    - ctng_sample
    - ctng_cpu_arch
    - ctng_binutils
    - ctng_target_platform
  - - ctng_gcc
    - libgfortran_soname
