ctng_cpu_arch:
  - x86_64
  - powerpc64le
  - aarch64
  - s390x
ctng_vendor:
  - conda
ctng_gcc:
  - 7.5.0
  - 8.4.0
  - 9.3.0
libgfortran_soname:
  - 4
  - 5
  - 5
ctng_binutils:
  - 2.36.1
ctng_target_platform:
  - linux-64
  - linux-ppc64le
  - linux-aarch64
  - linux-s390x
old_ctng_vendor:
  - conda_cos6
  - conda_cos7
  - conda_cos7
  - conda_cos7
ctng_gcc_build_number:
  - 20
conda_glibc_ver:
  - 2.12
  - 2.17
  - 2.17
  - 2.17
# openmp versions
openmp_ver:
  - 4.5
libgomp_ver:
  - 1.0.0
_libgcc_mutex:
  - 0.1 conda_forge
channel_targets:
  - conda-forge gcc_dev
zip_keys:
  - - conda_glibc_ver
    - old_ctng_vendor
    - ctng_cpu_arch
    - ctng_target_platform
  - - ctng_gcc
    - libgfortran_soname
